name: gutils
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - antlr-python-runtime=4.7.2
  - asttokens=2.2.1
  - attr=2.5.1
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - cc-plugin-glider=1.0.6
  - certifi=2023.5.7
  - cf-units=3.1.1
  - cffi=1.15.1
  - cfgv=3.3.1
  - cftime=1.6.1
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - compliance-checker=5.0.2
  - contourpy=1.0.7
  - cryptography=41.0.1
  - curl=8.1.2
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=5.1.1
  - distlib=0.3.6
  - exceptiongroup=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - filelock=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.0
  - freetype=2.12.1
  - geos=3.11.0
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - graphite2=1.3.13
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - gsw=3.4.0
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - identify=2.5.19
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib-resources=5.12.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - ipdb=0.13.11
  - ipython=8.11.0
  - isodate=0.6.1
  - jack=1.9.22
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libsndfile=1.2.0
  - libsqlite=3.40.0
  - libssh2=1.11.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mpg123=1.31.2
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.3
  - netcdf4=1.6.0
  - nodeenv=1.7.0
  - nspr=4.35
  - nss=3.88
  - numpy=1.19.5
  - openjpeg=2.5.0
  - openssl=3.1.1
  - owslib=0.28.1
  - packaging=23.0
  - pandas=1.4.4
  - parso=0.8.3
  - pcre2=10.40
  - pendulum=2.1.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - platformdirs=3.1.0
  - pluggy=1.0.0
  - ply=3.11
  - pocean-core=3.0.0
  - pooch=1.7.0
  - pre-commit=3.1.1
  - proj=9.2.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygeoif=1.0.0
  - pygments=2.14.0
  - pyinotify=0.9.6
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyproj=3.6.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - pytest=7.2.2
  - pytest-sugar=0.9.7
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.7.1
  - pytzdata=2020.1
  - pyyaml=6.0
  - qt-main=5.15.6
  - readline=8.1.2
  - regex=2022.10.31
  - requests=2.28.2
  - scipy=1.9.1
  - setuptools=67.6.0
  - shapely=1.8.4
  - simplejson=3.18.3
  - sip=6.7.7
  - six=1.16.0
  - sqlite=3.40.0
  - stack_data=0.6.2
  - termcolor=2.3.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - udunits2=2.2.28
  - ukkonen=1.0.1
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - validators=0.20.0
  - virtualenv=20.20.0
  - wcwidth=0.2.6
  - wheel=0.38.4
  - whichcraft=0.6.1
  - xarray=2022.9.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - -r requirements.txt
